Crear un administrador
POST http://localhost:5000/administradores
Content-Type: application/json


{
    "name": "A Berrio",
    "email": "Alejandro@developer.com",
    "password": "Danda1214",
    "confPassword": "Danda1214",
    "role": "Administrador"
}